# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0002_auto_20170412_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apikey',
            field=models.CharField(max_length=50),
        ),
    ]
