# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0006_auto_20170418_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionTrainingDescription',
            fields=[
                ('professiontraining_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2.ProfessionTraining')),
                ('description_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
            bases=('gw2.professiontraining',),
        ),
    ]
