# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0007_professiontrainingdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('profession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2.Profession')),
                ('weapon_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('gw2.profession',),
        ),
        migrations.CreateModel(
            name='WeaponDescription',
            fields=[
                ('weapons_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2.Weapons')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_slot', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
            bases=('gw2.weapons',),
        ),
    ]
