# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0008_weapondescription_weapons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profession',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='professiontraining',
            name='profession_ptr',
        ),
        migrations.RemoveField(
            model_name='professiontrainingdescription',
            name='professiontraining_ptr',
        ),
        migrations.RemoveField(
            model_name='weapondescription',
            name='weapons_ptr',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='profession_ptr',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='ProfessionTraining',
        ),
        migrations.DeleteModel(
            name='ProfessionTrainingDescription',
        ),
        migrations.DeleteModel(
            name='WeaponDescription',
        ),
        migrations.DeleteModel(
            name='Weapons',
        ),
    ]
